import "./globals.css";
import '@fontsource/montserrat'; // Default weight 400
import '@fontsource/montserrat/700.css'; // Specific weight


export const metadata = {
  title: "NFDP Feedback",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
